# Part 1 - Numpy

In [10]:
import numpy as np
import pandas as pd
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

1. ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.


In [11]:
A = iris[0].reshape(1,-1)
B = iris[1].reshape(1,-1)

In [12]:
A

array([[5.1, 3.5, 1.4, 0.2]])

In [13]:
B

array([[4.9, 3. , 1.4, 0.2]])

In [14]:
print(A.shape)
print(B.shape)

(1, 4)
(1, 4)


In [15]:
A_B_v=np.concatenate((A,B),axis=0)
A_B_h=np.concatenate((A,B),axis=1)
print(A_B_h)
print(A_B_v)

[[5.1 3.5 1.4 0.2 4.9 3.  1.4 0.2]]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]]


2. ⁠Find common elements between A and B. [Hint : Intersection of two sets]

In [16]:
inter =np.intersect1d(A,B)
inter

array([0.2, 1.4])

3.⁠ ⁠Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]


In [17]:
A_range=A[np.where((A>1) & (A<=5))]
A_range

array([3.5, 1.4])

4.⁠ ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0


In [18]:
selection=iris[(iris[:,2]>1.5) & (iris[:,0]<5.0)]
selection

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

# Part 2 - Numpy

1. ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [19]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df[1::20][['Manufacturer', 'Model','Type']]

Manufacturer     Model     Type
1           NaN    Legend  Midsize
21     Chrysler  Imperial    Large
41        Honda     Civic    Small
61   Mitsubishi    Mirage    Small
81       Subaru    Legacy  Compact

2. ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [20]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df[['Min.Price','Max.Price']].isnull().sum())
df['Min.Price']=df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price']=df['Max.Price'].fillna(df['Max.Price'].mean())
df[['Min.Price','Max.Price']]
print(df[['Min.Price','Max.Price']].isnull().sum())

Min.Price    7
Max.Price    5
dtype: int64
Min.Price    0
Max.Price    0
dtype: int64


3.  ⁠How to get the rows of a dataframe with row sum > 100?

In [21]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

df[df.sum(axis=1)>100]

0   1   2   3
2   32  37  14  22
7   24  32  35  15
8   12  15  36  38
9   33  32  22  30
10  24  17  31  35
12  34  36  12  39